### ISSUE TITLE
Glade EDA not invoking from Visual Studio

### ISSUE THREAD

**Issue by engrvip** [eskiyerli/revEDAsetup#3]
Hi Murat,

Was trying to invoke Glade from inside Visual Studio but it is not invoking.
GIF file attached for reference. Please suggest how to rectify it. 

Thanks
Vipul

![image](https://user-images.githubusercontent.com/84322258/145718811-efed2871-b31f-48e2-9497-9647daf0fdc1.png)

![j0QEKbHhAn](https://user-images.githubusercontent.com/84322258/145718735-4d107afd-d2f0-470e-be1f-60e6962a84ca.gif)

**Comment by eskiyerli** [comment]
I can think of two possibilities:

1. You need to first run docker compose down before running 'docker compose up'
2. I have been working on the image today and you somehow run into a problem because I was uploading the new image.

If it does not work after you try the first solution, could you please let me know?

Regards,

Murat

**Comment by eskiyerli** [comment]
Hello, were you able to resolve this problem?
